"""baseline schema

Revision ID: 639fcc5ce04c
Revises: 
Create Date: 2026-07-23 14:13:44.446570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639fcc5ce04c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('portal_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code')
    )
    op.create_table('fire_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('raw_properties', sa.Text(), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    op.create_table('fire_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('locality_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat_rounded', sa.Float(), nullable=False),
    sa.Column('lon_rounded', sa.Float(), nullable=False),
    sa.Column('locality_name', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('hashtag', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_rounded', 'lon_rounded', name='uq_lat_lon_rounded')
    )
    op.create_table('place_geocode_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_normalized', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_normalized', name='uq_place_geocode_query')
    )
    op.create_table('regional_incident_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('portal_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code')
    )
    op.create_table('source_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('last_message_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('hashtag_location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webcams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('road', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_webcam_source_external_id')
    )
    op.create_table('admin_bulletins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['admin_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'file_url', name='uq_source_file_url')
    )
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['fire_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regional_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('controlled_at', sa.DateTime(), nullable=True),
    sa.Column('extinguished_at', sa.DateTime(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('cause', sa.String(length=255), nullable=True),
    sa.Column('personnel_summary', sa.Text(), nullable=True),
    sa.Column('matched_incident_id', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_incident_id'], ['fire_incidents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['regional_incident_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_regional_source_external_id')
    )
    op.create_table('satellite_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('collection', sa.String(length=50), nullable=False),
    sa.Column('scene_id', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('item_url', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['fire_incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'collection', 'scene_id', name='uq_incident_collection_scene')
    )
    op.create_table('telegram_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_path', sa.String(length=500), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('matched_incident_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.id'], ),
    sa.ForeignKeyConstraint(['matched_incident_id'], ['fire_incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='uq_channel_message_id')
    )
    op.create_table('copernicus_ems_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('activation_time', sa.DateTime(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('n_aois', sa.Integer(), nullable=True),
    sa.Column('n_products', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('activator', sa.String(length=500), nullable=True),
    sa.Column('report_link', sa.String(length=1000), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.Column('matched_incident_id', sa.Integer(), nullable=True),
    sa.Column('incident_event_id', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_event_id'], ['incident_events.id'], ),
    sa.ForeignKeyConstraint(['matched_incident_id'], ['fire_incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_ems_activation_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copernicus_ems_activations')
    op.drop_table('telegram_messages')
    op.drop_table('satellite_scenes')
    op.drop_table('regional_incidents')
    op.drop_table('incident_events')
    op.drop_table('admin_bulletins')
    op.drop_table('webcams')
    op.drop_table('user_reports')
    op.drop_table('telegram_channels')
    op.drop_table('source_checks')
    op.drop_table('regional_incident_sources')
    op.drop_table('place_geocode_cache')
    op.drop_table('locality_cache')
    op.drop_table('fire_incidents')
    op.drop_table('fire_detections')
    op.drop_table('admin_sources')
    # ### end Alembic commands ###
