"""add fire detections spatial index

Revision ID: 8d49e66c5095
Revises: d4790580a545
Create Date: 2026-08-05 15:07:23.780860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d49e66c5095'
down_revision: Union[str, Sequence[str], None] = 'd4790580a545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fire_detections_acquired_lat_lon', 'fire_detections', ['acquired_at', 'latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fire_detections_acquired_lat_lon', table_name='fire_detections')
    # ### end Alembic commands ###
