"""add copernicus ems products

Revision ID: d4790580a545
Revises: 639fcc5ce04c
Create Date: 2026-07-23 19:35:51.031631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4790580a545'
down_revision: Union[str, Sequence[str], None] = '639fcc5ce04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copernicus_ems_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activation_id', sa.Integer(), nullable=False),
    sa.Column('aoi_number', sa.Integer(), nullable=False),
    sa.Column('aoi_name', sa.String(length=255), nullable=True),
    sa.Column('monitoring_number', sa.Integer(), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.Column('cog_url', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activation_id'], ['copernicus_ems_activations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_id', 'aoi_number', name='uq_ems_activation_aoi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copernicus_ems_products')
    # ### end Alembic commands ###
